#############################################################################
# Makefile for building: bin/dgfConfig
# Generated by qmake (2.01a) (Qt 4.8.1) on: Mon Oct 14 16:47:18 2013
# Project:  dgfConfig.pro
# Template: app
# Command: /home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake -spec /home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++ -o Makefile dgfConfig.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++ -I. -I/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/include/QtCore -I/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/include/QtGui -I/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/include -Imoc -Iui
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/lib
LIBS          = $(SUBLIBS)  -L/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/lib -lQtGui -L/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/main.cpp \
		src/dgfconfig.cpp \
		src/psasettings.cpp moc/moc_dgfconfig.cpp \
		moc/moc_psasettings.cpp
OBJECTS       = obj/main.o \
		obj/dgfconfig.o \
		obj/psasettings.o \
		obj/moc_dgfconfig.o \
		obj/moc_psasettings.o
DIST          = /home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/linux.conf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-unix.conf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-unix.conf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/release.prf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		dgfConfig.pro
QMAKE_TARGET  = dgfConfig
DESTDIR       = bin/
TARGET        = bin/dgfConfig

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui/ui_dgfconfig.h ui/ui_psasettings.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: dgfConfig.pro  /home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++/qmake.conf /home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/linux.conf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-unix.conf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-unix.conf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/release.prf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtGui.prl \
		/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtCore.prl
	$(QMAKE) -spec /home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++ -o Makefile dgfConfig.pro
/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf:
/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/linux.conf:
/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf:
/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-unix.conf:
/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf:
/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-unix.conf:
/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri:
/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri:
/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf:
/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf:
/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf:
/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf:
/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/release.prf:
/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf:
/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf:
/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf:
/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf:
/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf:
/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf:
/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf:
/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf:
/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf:
/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf:
/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtGui.prl:
/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++ -o Makefile dgfConfig.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/dgfConfig1.0.0 || $(MKDIR) obj/dgfConfig1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/dgfConfig1.0.0/ && $(COPY_FILE) --parents src/dgfconfig.h src/psasettings.h obj/dgfConfig1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/dgfconfig.cpp src/psasettings.cpp obj/dgfConfig1.0.0/ && $(COPY_FILE) --parents src/dgfconfig.ui src/psasettings.ui obj/dgfConfig1.0.0/ && (cd `dirname obj/dgfConfig1.0.0` && $(TAR) dgfConfig1.0.0.tar dgfConfig1.0.0 && $(COMPRESS) dgfConfig1.0.0.tar) && $(MOVE) `dirname obj/dgfConfig1.0.0`/dgfConfig1.0.0.tar.gz . && $(DEL_FILE) -r obj/dgfConfig1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc/moc_dgfconfig.cpp moc/moc_psasettings.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_dgfconfig.cpp moc/moc_psasettings.cpp
moc/moc_dgfconfig.cpp: src/dgfconfig.h
	/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) src/dgfconfig.h -o moc/moc_dgfconfig.cpp

moc/moc_psasettings.cpp: src/psasettings.h
	/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) src/psasettings.h -o moc/moc_psasettings.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui/ui_dgfconfig.h ui/ui_psasettings.h
compiler_uic_clean:
	-$(DEL_FILE) ui/ui_dgfconfig.h ui/ui_psasettings.h
ui/ui_dgfconfig.h: src/dgfconfig.ui
	/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/bin/uic src/dgfconfig.ui -o ui/ui_dgfconfig.h

ui/ui_psasettings.h: src/psasettings.ui
	/home/pscholz/programs/QtSDK/Desktop/Qt/4.8.1/gcc/bin/uic src/psasettings.ui -o ui/ui_psasettings.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

obj/main.o: src/main.cpp src/dgfconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/dgfconfig.o: src/dgfconfig.cpp src/dgfconfig.h \
		ui/ui_dgfconfig.h \
		src/psasettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/dgfconfig.o src/dgfconfig.cpp

obj/psasettings.o: src/psasettings.cpp src/psasettings.h \
		ui/ui_psasettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/psasettings.o src/psasettings.cpp

obj/moc_dgfconfig.o: moc/moc_dgfconfig.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_dgfconfig.o moc/moc_dgfconfig.cpp

obj/moc_psasettings.o: moc/moc_psasettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_psasettings.o moc/moc_psasettings.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

